services:
  notification-service:
    build:
      context: ../../
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    restart: unless-stopped
    expose:
      - "4000"
    env_file:
      - ./notification.env
    networks:
      - backend

networks:
  backend:
    external: true
