services:
  user-service:
    build:
      context: ../../
      dockerfile: user-service/Dockerfile
    container_name: user-service
    restart: unless-stopped
    depends_on:
      - user-redis
      - user-db-shard-0
      - user-db-shard-1
    env_file:
      - ./user.env
    ports:
      - "${HTTP_EXTERNAL_PORT}:${HTTP_PORT}"
    networks:
      - backend

  user-redis:
    image: redis:7
    container_name: user-redis
    restart: unless-stopped
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
    volumes:
      - user_redis_data:/data
    networks:
      - backend

  user-db-shard-0:
    image: postgres:15
    container_name: user-db-shard-0
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME_0}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT_0}:${DB_PORT}"
    volumes:
      - user_db_shard_0_data:/var/lib/postgresql/data
    networks:
      - backend

  user-db-shard-1:
    image: postgres:15
    container_name: user-db-shard-1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME_1}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT_1}:${DB_PORT}"
    volumes:
      - user_db_shard_1_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  user_redis_data:
  user_db_shard_0_data:
  user_db_shard_1_data:

networks:
  backend:
    external: true