services:
  cart-service:
    build:
      context: ../../
      dockerfile: cart-service/Dockerfile
    container_name: cart-service
    restart: unless-stopped
    expose:
      - "4000"
    depends_on:
      - cart-redis
    env_file:
      - ./cart.env
    networks:
      - backend

  cart-redis:
    image: redis:7
    container_name: cart-redis
    restart: unless-stopped
    volumes:
      - cart_redis_data:/data
    networks:
      - backend

volumes:
  cart_redis_data:

networks:
  backend:
    external: true
