services:
  api-gateway:
    build:
      context: ../../
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "80:8000"
    env_file:
      - ./gateway.env
    networks:
      - backend

networks:
  backend:
    external: true
