services:
  api-gateway:
    build:
      context: ../../
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - ./gateway.env
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`localhost`)"
      - "traefik.http.routers.api-gateway.entrypoints=web"
      - "traefik.http.services.api-gateway.loadbalancer.server.port=8000"

networks:
  backend:
    external: true
