global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'catalog-service'
    static_configs:
      - targets: ['catalog-service:8080']

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:8080']
