services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=backend"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=INFO"
      # Для Prometheus
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.01,0.05,0.1,0.25,0.5,1.0,2.5,5.0"
    ports:
      - "80:80"
      - "8080:8080"
