services:
  catalog-service:
    build:
      context: ../../
      dockerfile: catalog-service/Dockerfile
    container_name: catalog-service
    restart: unless-stopped
    expose:
      - "4000"
      - "50051"
    depends_on:
      - catalog-db
    env_file:
      - ./catalog.env
    networks:
      - backend

  catalog-db:
    image: postgres:15
    container_name: catalog-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - catalog_db_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  catalog_db_data:

networks:
  backend:
    external: true
